### ISSUE TITLE
Workflow not producing viewable results

### ISSUE THREAD

**Issue by cmccoy1** [parameterspace-ie/eo4a-service-trials#10]
I created a simple workflow in November (https://portal.eo4a.science/workflows/772) and this produced the appropriate output images. However, when I try to create the exact same workflow now and execute it (https://portal.eo4a.science/workflows/901), the job completes successfully, but no preview images appear and no new image outputs are added to the 'Layers':
(https://portal.eo4a.science/workspace/exec/902)

**Comment by derekocallaghan** [comment]
Hi Calvin,

This is a bug in the Sentinel-2 RGB service, where it isn't finding the band 4, 3, 2 rasters in the input L1C Sentinel-2 products. The 'RGB Test'  workflow (https://portal.eo4a.science/workflows/772) specifies a L2A product which can be successfully processed, while 'RGB New Test' specifies a L1C product resulting in no preview image for the corresponding job at https://portal.eo4a.science/workspace/exec/902. 

We plan to have a fix for this in the next release. In the meantime, any L2A products, or L3A outputs from the Sen2Three service should be fine as inputs to the Sentinel-2 RGB service.

Derek

**Comment by cmccoy1** [comment]
Hi Derek,

Thanks for your response. I've had a go with just Sentinel-2 L2A products and got some working now. However, I'm still having problems with the outputs from other jobs not being viewable. Could you have a look at jobs 923 and 927. 923 is a terrain flattening Sentinel-1 GRD workflow and 927 is a simple RGB workflow with a subset service added ( I also tried this workflow with the subset service before the RGB service as per job 925, but this job failed). Both say they completed successfully but again I don't seem to have any previews available or any new layers to add to the map viewer.

Thanks

**Comment by anajura-ps** [comment]
Hi Calvin,

Thank you for your reports.

Both jobs you mentioned above produced outputs, but are not creating a layer.

If you go to the job page again, at the bottom is red button with EO4Atlantic Pathfinder text. That will take you to the list of all task directories and within are all outputs, which you can then download.
For example, I just downloaded Gamma0_VH.img and Gamma0_VH.hdr from eotools.terrain_flattening_pipeline/output/terrainflattened/ directory in your job 923 (terrain flattening). When displayed in QGIS, the file looks correct.

The job 927 is also producing outputs which you can see by clicking the mentioned EO4Atlantic Pathfinder button. However, the subset task does not produce tif files, which Publish Raster Layers service is expecting (file_pattern input is *.tif).

Ana

**Comment by cmccoy1** [comment]
Thanks for the response Ana,

I'll try that and see how they look in QGIS.

Thanks...

**Comment by anajura-ps** [comment]
Just the suggestion, you can take a look at one of our examples:
https://docs.eo4a.science/example_wf.html#terrain-correction-of-irish-lake-region

The Terrain Correction Pipeline has the layer_dir (containing tif files) as one of outputs, which can be connected to Publish Raster Layer and produce layers. 

We might do the same for Terrain Flattening Pipeline for the next release.
