### ISSUE TITLE
NDVI and other Ratio images

### ISSUE THREAD

**Issue by cmccoy1** [parameterspace-ie/eo4a-service-trials#11]
Hi,

Would you mind taking a look at jobs 931 and 937? I'm just trying to create a simple NBR ratio image with two services: Copernicus and Band Math. Perhaps I have the syntax wrong? (I've written the syntax in job 937 exactly as I would write it in SNAP). Also, does it matter that both bands have got different spatial resolutions, because I always have to resample band 12 in SNAP before I can carry out band math for a NBR image?

Thanks

**Comment by anajura-ps** [comment]
Hi Calvin,

Thank you for your report. 
There is a bug in Band Maths service that we did not notice before. The service does not work properly with Sentinel-2 data, the problem was not in the syntax. This will be fixed for the February release.

Ana

**Comment by anajura-ps** [comment]
This Band Maths bug is now fixed and the examples of proper syntax are given in both User Guide and Band Maths' expression input abstract. The improvements will be available in 0.2.9 (February 2018) release of the EO4Atlantic platform.

**Comment by anajura-ps** [comment]
Closing, as this Band Maths bug fix has been deployed and successfully tested.
