### ISSUE TITLE
Starting EO4A services Issue

### ISSUE THREAD

**Issue by diplonics** [parameterspace-ie/eo4a-service-trials#13]
Hi Derek, 
    the following snippet is from the output of our development platform startup.
Probably something obvious to fix it as no other obvious errors occur but I'm not sure.

Paul

```
------------------------------------------------------------
Waiting for service container to respond...
------------------------------------------------------------
.........It's up
------------------------------------------------------------
Reloading the available WPS services
------------------------------------------------------------
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>

------------------------------------------------------------
FINISHED
------------------------------------------------------------
```

**Comment by derekocallaghan** [comment]
Hi Paul,

This is not a problem as such, it looks like the corresponding WPS services in your git repo haven't been reloaded within the default 3 seconds. I'll assume that reloading from a notebook is working as expected. The timeout will be increased in the next release, but if services take a long time to load for some reason, then it may happen again. If it's working in a notebook, it can be ignored.

Derek
