### ISSUE TITLE
New service not visible in workflows

### ISSUE THREAD

**Issue by jhanafin** [parameterspace-ie/eo4a-service-trials#14]
The iCOR atmospheric correction service provided as a github repo in December does not appear in the list of available services to use in a workflow. Please advise on how testing should proceed.

**Comment by derekocallaghan** [comment]
The iterative integration process is described in the "EO4Atlantic service integration" mail from Sinead on 2017/12/14. Specifically, the Git commit hash for the repository must be provided to PS in order for a particular version of a service to be integrated.

However, the current version of the 'icor' service will not be successfully integrated as the 'metadata' attribute is empty (line 228 in https://github.com/techworksmarine/eo4a_service/blob/master/icor/wps.py). The 'metadata' list should contain a single 'Metadata' instance, which corresponds to its preferred menu location in the EO4Atlantic workflow builder. An example can be seen at line 96 in https://github.com/parameterspace-ie/eo4a-service-development/blob/develop/sentinel/wps.py 

We would suggest setting the metadata value to 'Metadata("Atmospheric")' to follow the convention used for the existing EO4Atlantic atmospheric correction services.

**Comment by jhanafin** [comment]
Thanks for the info Derek. We will edit teh metadata and resubmit the hash. It would have been useful to have received an indication before now that we had not provided the required information. We were under the impression that the service had been included as we had not received any feedback from PS or the platform to say otherwise.
