### ISSUE TITLE
Sentinel3 data downloader - number of products

### ISSUE THREAD

**Issue by jarekdobrzanski** [parameterspace-ie/eo4a-service-trials#15]
Is it possible to increase the maximum number product that can be downloaded from 2 to something in a range of 30? We'd need that to test our in-situ matchup service.

**Comment by derekocallaghan** [comment]
As discussed over email, 30 products cannot be supported in the pathfinder platform. We can raise the limit from 2 to 5, this will be deployed when deploying the first version of your matchup service.

**Comment by derekocallaghan** [comment]
Closing as the limit of 5 has been deployed and successfully tested.
