### ISSUE TITLE
HTTPError: 502 Server Error

### ISSUE THREAD

**Issue by dairejpwalsh** [parameterspace-ie/eo4a-service-trials#17]
I'm getting the following error half way through my script,

HTTPError: 502 Server Error: Bad Gateway for url: http://127.0.0.1/wps

Does anyone know what may be causing this?

**Comment by dairejpwalsh** [comment]
I found a solution for this. By setting
```
 output='output_reference'
```
for 
```
wps.execute()
```
I no longer get an error. Still unsure why this has fixed the issue.

**Comment by derekocallaghan** [comment]
Good to hear you have it working. I'd have to see the Docker logs etc to confirm, but I suspect it's a timeout issue happening with synchronous execution of the service code called via `wps.execute()`. Specifying the `output_reference` as you're doing will ensure asynchronous execution. 

Services integrated in the platform itself are always executed asynchronously so in theory this shouldn't be an issue when it's integrated.

**Comment by derekocallaghan** [comment]
Closing as asynchronous execution resolves the issue.
