### ISSUE TITLE
Switching to own service container

### ISSUE THREAD

**Issue by jarekdobrzanski** [parameterspace-ie/eo4a-service-trials#2]
It seems that in order to set the env vars so that they point to my own local repo with services a rebuild of the container is required as in:
```
docker stop container
docker rm container
```
and then run` bin/eo4adev` again.

That gets me the initial state of container and it won't load my WPS sevices as they are not there yet. Only after re-creating the container I can pull my services in from github but then how can I get them to be acknowledged and re-loaded as WPS services?

Might be somehow related to #1

**Comment by derekocallaghan** [comment]
Hi Jarek,

Once the container has been created with eo4adev, you can run 'docker stop', 'docker start' as required. However, with a running container, you can reload any of your services with the following command in a notebook:

'reload_services(wps)'

See cell [2] in https://github.com/parameterspace-ie/eo4a-service-development/blob/master/notebooks/run_eo4a_service.ipynb

Derek

**Comment by jarekdobrzanski** [comment]
Issue resolved with answer to #1
