### ISSUE TITLE
Matchups integration - parameters passed to service command

### ISSUE THREAD

**Issue by jarekdobrzanski** [parameterspace-ie/eo4a-service-trials#20]
We've created a workflow called 'matchups_test_Feb2018' and run it as job 1194. We're getting a following error runing Matchups service:
```

Process error: EO4AProcess.py._run_process Line 384 task: non-zero exit (2)
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
usage: wrapper.py [-h] [--in_situ_data IN_SITU_DATA] [--parameter PARAMETER]
                  [--latitude LATITUDE] [--longitude LONGITUDE]
                  [--match_radius MATCH_RADIUS]
                  [--time_tolerance TIME_TOLERANCE] [--input_dir INPUT_DIR]
                  output_dir
wrapper.py: error: unrecognized arguments: 0.45, 2018-02-25 13:35:20, 10.5 --user_api_key api_key_1015 --username jdobrzanski --workflow_id bb09461f-e6ce-48cc-b237-a8757a0e405d --user_session None twm.matchups/output
```
Looks like the arguments are beings passed in a different way in the platform and standalone mode, and there's some platform specific parameters passed as well. Please suggest the way forward.

**Comment by derekocallaghan** [comment]
This is most likely due to the use of a single `in_situ_data` parameter to pass multiple values, which is not recommended as it is likely to result in errors by the end user. However, it may be the case that it could be resolved by removing the spaces in the input values, where only comma separators are used in all cases.

**Comment by jarekdobrzanski** [comment]
I'm wrapping all parameters in double quotes in get_command to prevent this type of issues, so the only thing that comes to my mind is that on the platform there's some additional string parsing/formatting step that might break the quotes. The quotes are now escaped so hopefully that will resolve the problem and some more logging added to see what is happening.

**Comment by derekocallaghan** [comment]
The WPS server will wrap any parameter values containing spaces in double quotes, this is what was seen in the logs last time.

We recommend removing spaces altogether, as it looks like you can get by solely with comma separators.

**Comment by jarekdobrzanski** [comment]
I can just test without spaces now and if it's fine I'll just add space stripping, and if we still have problems with broken quotes I'll remove my wrapping and add space stripping only

**Comment by jarekdobrzanski** [comment]
The wrapper is now adapted to take platform related arguments and in-situ-data timestamp format with no spaces

**Comment by derekocallaghan** [comment]
Closing as this issue was resolved.
