### ISSUE TITLE
Passing the environment variables to execution

### ISSUE THREAD

**Issue by jarekdobrzanski** [parameterspace-ie/eo4a-service-trials#3]
Is there a way to pass an environment variable to the execution context of the command I'm wrapping? For instance I need to pass ICOR_PATH variable to the context executing my command.

**Comment by derekocallaghan** [comment]
Hi Jarek,

No, we don't support setting environment variables for individual services. I assume that you're installing ICOR in an install_dependencies.sh script, so I would suggest using the same location when running it from your WPS command script. 

Derek
