### ISSUE TITLE
bin/eo4adev Install Utility fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by diplonics** [parameterspace-ie/eo4a-service-trials#4]
The following error is reported on Ubuntu 14.04 when trying to install the bin/eo4adev Install Utility.
The install is fine on Ubuntu 16.04..
------------------------------------------------------------
Retrieving the EO4A Service container image
------------------------------------------------------------
WARNING: make sure you have already run 'docker login repositories.eo4a.science -u guest -p <password>'
Pulling the container image: repositories.eo4a.science/eo4a-service-framework-standalone:develop
failed to register layer: Error processing tar file(exit status 1): write /opt/conda/lib/libmkl_vml_mc.so: no space left on device
ERROR - Something went wrong while pulling the image. Please ensure you have run the 'docker login' command. Otherwise, contact (info [at] parameterspace.ie) for help.

**Comment by derekocallaghan** [comment]
Hi Paul,

This line "Error processing tar file(exit status 1): write /opt/conda/lib/libmkl_vml_mc.so: no space left on device" suggest that the local volume used to store Docker images is full.

Can you run `docker info` and search for the lines:

```
...
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
...
```

Next, check the available space on the volume containing the `Root Dir`. I assume it's (close to) 0%.

Derek

**Comment by diplonics** [comment]
Hi Derek,
       Out put as follows:
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       24G   21G  1.7G  93% /var/lib/docker/aufs

Almost full but obviously still not enough space at 1.7GB available.
I'll clean up a few bits and report back if it makes a difference.

Paul

**Comment by diplonics** [comment]
Hi Derek,
        Cleaned out another 5GB and tried again and installed fine so issue closed!!

Paul

**Comment by derekocallaghan** [comment]
Great, thanks Paul. I'll close the issue now.
