### ISSUE TITLE
Sen2Three seems that is not working for our tiles

### ISSUE THREAD

**Issue by japoveda** [parameterspace-ie/eo4a-service-trials#5]
We are running the Copernicus services as input to the Sen2Three. The output of  Sen2Three is the same that the input. We tried with these two Sentinel 2 data:

S2A_MSIL2A_20170504T115401_N0205_R023_T29UNA_20170504T115402
and 
S2A_MSIL2A_20170620T114351_N0205_R123_T29UNA_20170620T114348

Note that some days ago we run the services successfully, and we had an output with the MSIL03 level of proccessing (S2A_MSIL03_20170921T115401_N0205_R023_T29UNT_20160101T000000)

**Comment by derekocallaghan** [comment]
Hi Alex,

- Can you specify the URL of both this job, and the job that was previously successful?
- Was the same workflow used for both jobs?
- If so, was the workflow definition (different tasks, task parameters etc) modified between both job executions?

Derek

**Comment by japoveda** [comment]
Hi Derek,

This is working know, it was an issue in our side because the resolution was not defined.
You can close this Issue.

Thank you.

https://portal.eo4a.science/workspace/exec/837/
