### ISSUE TITLE
Feedback on tutorial (October 2017)

### ISSUE THREAD

**Issue by jhanafin** [parameterspace-ie/eo4a-service-trials#7]
Hi, here are some issues I ran into when going through your online tutorial. They may be fixed by now, but I thought I'd put them here so you can track if not. 

Added WMS from CMEMS, which worked well and all variables from the data product came up as an option to add as layer. Comment on visualisation, though, I can’t see what the colour bar refers to, either in units or values. Same on map, an option to show value under cursor would be a valuable tool. 
 
![image](https://user-images.githubusercontent.com/34307058/33828167-f48f7edc-de62-11e7-9a59-a3c355a49ce1.png)

In this layer, the values seem to be all below or at the minimum value, it would be great to be able to adjust colour bars so data can be made visible. 
 
![image](https://user-images.githubusercontent.com/34307058/33828171-fca62bca-de62-11e7-839d-bdc085dfb777.png)

In this day and age, I would expect netcdf file recognition to be standard:
 
![image](https://user-images.githubusercontent.com/34307058/33828178-00a6a178-de63-11e7-8ed4-2c429f10a522.png)
[PlatformTutorialFeedbackJHanafin.docx](https://github.com/parameterspace-ie/eo4a-service-trials/files/1547543/PlatformTutorialFeedbackJHanafin.docx)

These are all part of a Sentinel 3 file from the EUMETSAT hub, but there was no option to upload a folder, only individual files. I finally got a Landsat8 geotiff to start uploading, but it never finished.

**Comment by sineadmcglynn** [comment]
Hi Jenny,

Thanks for adding the feedback to the issue tracker. 

CMEMS WMS visualisation: This is dependent on the WMS format provided by the service provider  (i.e. not controlled by EO4A). Legends/colour bars are visible when the format is compliant with the WMS OGC standards and can't be changed.

NETCDF: Tiffs should upload without issue, but are size-dependent (very large files may not upload). NetCDFs are not supported in the prototype platform. 

Thanks!

Sinead.

**Comment by derekocallaghan** [comment]
Regarding "NetCDFs are not supported in the prototype platform", this is only true of EO4Atlantic support for NetCDF **layers** in maps (we note that NetCDF layers aren't currently universally supported by other similar applications/platforms). 

However, services that use NetCDF products **are** supported by EO4Atlantic, e.g. the CMEMS service: https://docs.eo4a.science/services/data.html#cmems
