### ISSUE TITLE
Copernicus and CEDA services

### ISSUE THREAD

**Issue by cmccoy1** [parameterspace-ie/eo4a-service-trials#9]
When I try to use the Copernicus or CEDA services, I can't search for imagery or draw a bounding box around my area of interest because the map viewer is just a black screen. Occasionally choosing 'Sentinel-2 Cloudless + Overlay' brings up a viewable Sentinel-2 map, but that seems to have stopped working now too. 

![blank map viewer](https://user-images.githubusercontent.com/34536630/33983764-40f3edb6-e0ad-11e7-81ed-b578d3d3bc24.PNG)

**Comment by anajura-ps** [comment]
Hi Calvin,

There seems to be an issue with rendering map for Copernicus Open Hub within the platform interface, possibly related to new visualization within Hub itself.  We will look into that.

Unfortunately, the map behaviour is unpredictable at the moment, so the way to view the map is to try zoom-in on the map or open Copernicus Hub in another tab or window and then try again in the portal.

Ana

**Comment by derekocallaghan** [comment]
Closing as this issue is with the use of the COAH interface, and the above workaround is to be used for the pathfinder.
